### ISSUE TITLE
Access to Intel(r) Performance Counter Monitor has denied (no MSR or PCI CFG space access).

### ISSUE THREAD

**Issue by JamesNolan17** [intellistream/AllianceDB#16]
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/61568403/129931330-17a1370c-f381-44ea-85e6-25ba7505ad28.png">

**Comment by ShuhaoZhangTony** [comment]
Need to enable vPMU in your virtual machine setting.

**Comment by JamesNolan17** [comment]
Noted
